name: Workflow commands

on:
  push:

jobs:
  workflow-commands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get author name
        id: author
        run: echo "::set-output name=author::$(git show -s --format=%an)"
      - name: Print author name
        run: echo "${{ steps.author.outputs.author }}"
      - name: Print author name with an environment variable
        run: echo $AUTHOR_NAME
        env:
          AUTHOR_NAME: ${{ steps.author.outputs.author }}
      - name: Log levels
        run: |
          echo "::debug::This is a debug message"
          echo "This is an info message"
          echo "::warning::This is a warning"
          echo "::error::This is an error"
      - name: Log grouping
        run: |
          echo "::group::Group name"
          echo "Log entry"
          echo "::warning::Warning message"
          echo "::endgroup::"
          echo "Outside the group"
      - name: Mask sensitive data
        run: |
          echo "::add-mask::password123"
          echo "My password is password123"
          echo "::add-mask::$SUPER_SECRET"
          echo "Here's a secret for you: $SUPER_SECRET"
        env:
          SUPER_SECRET: The cake is a lie.
